from django.db import models


# Create your models here.
class Win007(models.Model):
    datec = models.CharField(max_length=20, verbose_name=u'比赛日期')
    cc = models.CharField(max_length=20, verbose_name=u'场次')
    mar_right60 = models.CharField(max_length=20, verbose_name=u'推介', null=True)
    detail = models.TextField(verbose_name=u'详细情况', null=True)
    url = models.CharField(max_length=50, verbose_name=u'相关链接', null=True)
    mar_right1 = models.CharField(max_length=20, verbose_name=u'足球大贏家', null=True)
    mar_right2 = models.CharField(max_length=20, verbose_name=u'足彩大富翁', null=True)
    mar_right3 = models.CharField(max_length=20, verbose_name=u'明報', null=True)
    mar_right4 = models.CharField(max_length=20, verbose_name=u'太 陽 報', null=True)
    mar_right5 = models.CharField(max_length=20, verbose_name=u'東方日報', null=True)
    mar_right6 = models.CharField(max_length=20, verbose_name=u'蘋果日報', null=True)
    match_time = models.CharField(max_length=20, verbose_name=u'比赛时间', null=True)
    home_team = models.CharField(max_length=20, verbose_name=u'主队', null=True)
    guest_team = models.CharField(max_length=20, verbose_name=u'客队', null=True)
    h_odd = models.CharField(max_length=10, verbose_name=u'主胜赔率', null=True)
    pk_odd = models.CharField(max_length=10, verbose_name=u'打平赔率', null=True)
    g_odd = models.CharField(max_length=10, verbose_name=u'客胜赔率', null=True)
    full_result = models.CharField(max_length=10, verbose_name=u'比分', null=True)
    oddstr_281_f_result = models.CharField(max_length=30, verbose_name=u'bet365初盘', null=True)
    oddstr_281_l_result = models.CharField(max_length=30, verbose_name=u'bet365即时', null=True)
    oddstr_115_f_result = models.CharField(max_length=30, verbose_name=u'威廉希尔初盘', null=True)
    oddstr_115_l_result = models.CharField(max_length=30, verbose_name=u'威廉希尔即时', null=True)
    oddstr_82_f_result = models.CharField(max_length=30, verbose_name=u'立博初盘', null=True)
    oddstr_82_l_result = models.CharField(max_length=30, verbose_name=u'立博即时', null=True)
    odds_3_f_result = models.CharField(max_length=30, verbose_name=u'Crown初盘(亚)', null=True)
    odds_3_l_result = models.CharField(max_length=30, verbose_name=u'Crown即时(亚)', null=True)
    odds_8_f_result = models.CharField(max_length=30, verbose_name=u'Bet365初盘(亚)', null=True)
    odds_8_l_result = models.CharField(max_length=30, verbose_name=u'Bet365即时(亚)', null=True)
    odds_14_f_result = models.CharField(max_length=30, verbose_name=u'韦德初盘(亚)', null=True)
    odds_14_l_result = models.CharField(max_length=30, verbose_name=u'韦德即时(亚)', null=True)


class Zqfx(models.Model):
    datec = models.CharField(max_length=20, verbose_name=u'比赛日期')
    cc = models.CharField(max_length=20, verbose_name=u'场次')
    fxs_leauge = models.CharField(max_length=50, verbose_name=u'联赛', null=True)
    fxs_leauge_name0 = models.CharField(max_length=50, verbose_name=u'主队', null=True)
    fxs_leauge_name1 = models.CharField(max_length=50, verbose_name=u'客队', null=True)
    fxs_2_02_c01 = models.CharField(max_length=50, verbose_name=u'彩种1', null=True)
    fxs_2_02_c03 = models.CharField(max_length=50, verbose_name=u'推荐1', null=True)
    fxs_2_03_gailus1 = models.CharField(max_length=50, verbose_name=u'概率1', null=True)
    predictc = models.CharField(max_length=50, verbose_name=u'百分比', null=True)
    fxs_2_02_c01y = models.CharField(max_length=50, verbose_name=u'彩种2', null=True)
    fxs_2_02_c01yp = models.CharField(max_length=50, verbose_name=u'盘口2', null=True)
    fxs_2_02_c01yt = models.CharField(max_length=50, verbose_name=u'推荐2', null=True)
    fxs_2_02_c01yg = models.CharField(max_length=50, verbose_name=u'概率2', null=True)
    url = models.CharField(max_length=100, verbose_name=u'相关链接', null=True)

class Vipc(models.Model):
    datec = models.CharField(max_length=20, verbose_name=u'比赛日期')
    cc = models.CharField(max_length=20, verbose_name=u'场次')
    win = models.CharField(max_length=20, verbose_name=u'主队概率', null=True)
    lose = models.CharField(max_length=20, verbose_name=u'客队概率', null=True)
    result = models.CharField(max_length=20, verbose_name=u'结果', null=True)
    bf = models.CharField(max_length=20, verbose_name=u'预测比分', null=True)
    url = models.CharField(max_length=100, verbose_name=u'相关链接', null=True)
    home = models.CharField(max_length=100, verbose_name=u'主队', null=True)
    guest = models.CharField(max_length=100, verbose_name=u'客队', null=True)
    content = models.TextField( verbose_name=u'内容', null=True)
    matchId = models.CharField(max_length=100, verbose_name=u'比赛ID', null=True)
    ratio = models.CharField(max_length=100,verbose_name=u'赔率', null=True)
    num = models.CharField(max_length=100,verbose_name=u'投注人数', null=True)
    betting = models.CharField(max_length=100,verbose_name=u'投注比率', null=True)
    suggest0 = models.CharField(max_length=100,verbose_name=u'建议', null=True)
    letgoal = models.CharField(max_length=100,verbose_name=u'让球', null=True)
    suggest1 = models.CharField(max_length=100,verbose_name=u'建议', null=True)


class Tips(models.Model):
    datec = models.CharField(max_length=20, verbose_name=u'比赛日期')
    cc = models.CharField(max_length=20, verbose_name=u'场次')
    wjxs = models.CharField(max_length=50, verbose_name=u'往绩系数', null=True)
    slfx_left = models.TextField(verbose_name=u'实力分析(主)', null=True)
    slfx_right = models.TextField(verbose_name=u'实力分析(客)', null=True)
    sjfx_left = models.TextField(verbose_name=u'数据分析(主)', null=True)
    sjfx_rigft = models.TextField(verbose_name=u'数据分析(客)', null=True)
    wjjk_left = models.TextField(verbose_name=u'往绩近况(主)', null=True)
    wjjk_rigft = models.TextField(verbose_name=u'往绩近况(客)', null=True)
    op = models.CharField(max_length=100, verbose_name=u'欧赔', null=True)
    yp = models.CharField(max_length=100, verbose_name=u'亚赔', null=True)
    dzwj = models.CharField(max_length=500, verbose_name=u'对阵往绩', null=True)
    tencjk = models.CharField(max_length=500, verbose_name=u'10场近况', null=True)
    pmxd = models.CharField(max_length=500, verbose_name=u'排名相当', null=True)
    url = models.CharField(max_length=200, verbose_name=u'链接', null=True)
    home = models.CharField(max_length=100, verbose_name=u'主队', null=True)
    guest = models.CharField(max_length=100, verbose_name=u'客队', null=True)


class Leisu(models.Model):
    datec = models.CharField(max_length=20, verbose_name=u'比赛日期')
    cc = models.CharField(max_length=20, verbose_name=u'场次')
    team1 = models.CharField(max_length=50, verbose_name=u'主队', null=True)
    win = models.CharField(max_length=50, verbose_name=u'主队概率', null=True)
    team2 = models.CharField(max_length=50, verbose_name=u'客队', null=True)
    lose = models.CharField(max_length=50, verbose_name=u'客队概率', null=True)
    lsjf_left = models.CharField(max_length=500, verbose_name=u'历史交锋(主)', null=True)
    lsjf_right = models.CharField(max_length=500, verbose_name=u'历史交锋(客)', null=True)
    jqzj_left = models.CharField(max_length=500, verbose_name=u'近期战绩(主)', null=True)
    jqzj_right = models.CharField(max_length=500, verbose_name=u'近期战绩(客)', null=True)
    remarks = models.CharField(max_length=500, verbose_name=u'赛果概率', null=True)
    url = models.CharField(max_length=100, verbose_name=u'链接', null=True)
    information = models.TextField(verbose_name=u'咨询', null=True)

class Now1(models.Model):
    datec = models.CharField(max_length=20, verbose_name=u'比赛日期')
    cc = models.CharField(max_length=20, verbose_name=u'场次')
    league = models.CharField(max_length=50, verbose_name=u'联赛', null=True)
    zhu = models.CharField(max_length=50, verbose_name=u'主队', null=True)
    ke = models.CharField(max_length=50, verbose_name=u'客队', null=True)
    half = models.CharField(max_length=50, verbose_name=u'半场比分', null=True)
    full = models.CharField(max_length=50, verbose_name=u'全场比分', null=True)
    w = models.CharField(max_length=500, verbose_name=u'主胜赔率', null=True)
    p = models.CharField(max_length=500, verbose_name=u'平手赔率', null=True)
    l = models.CharField(max_length=500, verbose_name=u'客胜赔率', null=True)
    had_prs_name = models.CharField(max_length=50, verbose_name=u'胜平负', null=True)
    had_odds = models.CharField(max_length=50, verbose_name=u'胜平负奖金', null=True)
    hhad_prs_name = models.CharField(max_length=50, verbose_name=u'让球胜平负', null=True)
    hhad_odds = models.CharField(max_length=50, verbose_name=u'让球胜平负奖金', null=True)
    crs_prs_name = models.CharField(max_length=50, verbose_name=u'比分', null=True)
    crs_odds = models.CharField(max_length=50, verbose_name=u'比分奖金', null=True)
    ttg_prs_name = models.CharField(max_length=50, verbose_name=u'总进球', null=True)
    ttg_odds = models.CharField(max_length=50, verbose_name=u'总进球奖金', null=True)
    hafu_prs_name = models.CharField(max_length=50, verbose_name=u'半全场胜平负', null=True)
    hafu_odds = models.CharField(max_length=50, verbose_name=u'半全场胜平负奖金', null=True)
    had_h_rate = models.CharField(max_length=50, verbose_name=u'胜平负过关固定奖金(主胜赔率)', null=True)
    had_d_rate = models.CharField(max_length=50, verbose_name=u'胜平负过关固定奖金(平手赔率)', null=True)
    had_a_rate = models.CharField(max_length=50, verbose_name=u'胜平负过关固定奖金(客胜赔率)', null=True)
    same_result = models.CharField(max_length=50, verbose_name=u'相同赔率', null=True)
    detail = models.TextField( verbose_name=u'详细情况', null=True)


class Sporttery(models.Model):
    datec = models.CharField(max_length=20, verbose_name=u'比赛日期')
    cc = models.CharField(max_length=20, verbose_name=u'场次')
    league = models.CharField(max_length=50, verbose_name=u'联赛', null=True)
    zhu = models.CharField(max_length=50, verbose_name=u'主队', null=True)
    ke = models.CharField(max_length=50, verbose_name=u'客队', null=True)
    half = models.CharField(max_length=50, verbose_name=u'半场比分', null=True)
    full = models.CharField(max_length=50, verbose_name=u'全场比分', null=True)
    w = models.CharField(max_length=500, verbose_name=u'主胜赔率', null=True)
    p = models.CharField(max_length=500, verbose_name=u'平手赔率', null=True)
    l = models.CharField(max_length=500, verbose_name=u'客胜赔率', null=True)
    had_prs_name = models.CharField(max_length=50, verbose_name=u'胜平负', null=True)
    had_odds = models.CharField(max_length=50, verbose_name=u'胜平负奖金', null=True)
    hhad_prs_name = models.CharField(max_length=50, verbose_name=u'让球胜平负', null=True)
    hhad_odds = models.CharField(max_length=50, verbose_name=u'让球胜平负奖金', null=True)
    crs_prs_name = models.CharField(max_length=50, verbose_name=u'比分', null=True)
    crs_odds = models.CharField(max_length=50, verbose_name=u'比分奖金', null=True)
    ttg_prs_name = models.CharField(max_length=50, verbose_name=u'总进球', null=True)
    ttg_odds = models.CharField(max_length=50, verbose_name=u'总进球奖金', null=True)
    hafu_prs_name = models.CharField(max_length=50, verbose_name=u'半全场胜平负', null=True)
    hafu_odds = models.CharField(max_length=50, verbose_name=u'半全场胜平负奖金', null=True)
    had_h_rate = models.CharField(max_length=50, verbose_name=u'胜平负过关固定奖金(主胜赔率)', null=True)
    had_d_rate = models.CharField(max_length=50, verbose_name=u'胜平负过关固定奖金(平手赔率)', null=True)
    had_a_rate = models.CharField(max_length=50, verbose_name=u'胜平负过关固定奖金(客胜赔率)', null=True)
    same_result = models.CharField(max_length=50, verbose_name=u'相同赔率', null=True)
    detail = models.TextField( verbose_name=u'详细情况', null=True)


class AllInfoOrm(models.Model):
    datec = models.CharField(max_length=50)
    cc = models.CharField(max_length=50)
    fxs_leauge_name0 = models.CharField(max_length=50)
    fxs_leauge_name1 = models.CharField(max_length=50)
    fxs_leauge = models.CharField(max_length=50)
    match_time = models.CharField(max_length=50)
    h_odd = models.CharField(max_length=10, verbose_name=u'主胜赔率', null=True)
    pk_odd = models.CharField(max_length=10, verbose_name=u'打平赔率', null=True)
    g_odd = models.CharField(max_length=10, verbose_name=u'客胜赔率', null=True)
    fxs_2_02_c03 = models.CharField(max_length=50, verbose_name=u'推荐1', null=True)
    predictc = models.CharField(max_length=50, verbose_name=u'百分比', null=True)
    wjxs = models.CharField(max_length=50, verbose_name=u'往绩系数', null=True)
    dzwj = models.CharField(max_length=500, verbose_name=u'对阵往绩', null=True)
    tencjk = models.CharField(max_length=500, verbose_name=u'10场近况', null=True)
    mar_right60 = models.CharField(max_length=20, verbose_name=u'推介', null=True)
    mar_right1 = models.CharField(max_length=20, verbose_name=u'足球大贏家', null=True)
    mar_right2 = models.CharField(max_length=20, verbose_name=u'足彩大富翁', null=True)
    mar_right3 = models.CharField(max_length=20, verbose_name=u'明報', null=True)
    mar_right4 = models.CharField(max_length=20, verbose_name=u'太 陽 報', null=True)
    mar_right5 = models.CharField(max_length=20, verbose_name=u'東方日報', null=True)
    mar_right6 = models.CharField(max_length=20, verbose_name=u'蘋果日報', null=True)
    vipc_win = models.CharField(max_length=20, verbose_name=u'主队概率', null=True)
    vipc_lose = models.CharField(max_length=20, verbose_name=u'客队概率', null=True)
    result = models.CharField(max_length=20, verbose_name=u'结果', null=True)
    leisu_win = models.CharField(max_length=20, verbose_name=u'主队概率', null=True)
    leisu_lose = models.CharField(max_length=20, verbose_name=u'客队概率', null=True)
    remarks = models.CharField(max_length=500, verbose_name=u'赛果概率', null=True)
    had_prs_name = models.CharField(max_length=500, verbose_name=u'赛果概率', null=True)
    url = models.CharField(max_length=500)
    vipc_url = models.CharField(max_length=500)
    win007_url = models.CharField(max_length=500)
    leisu_url = models.CharField(max_length=500)
    tips_url = models.CharField(max_length=500)
    live500_url = models.CharField(max_length=500)

    class Meta:
        db_table = 'all_list'