# Generated by Django 2.1.3 on 2019-12-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Win007',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datec', models.CharField(max_length=20, verbose_name='比赛日期')),
                ('cc', models.CharField(max_length=20, verbose_name='场次')),
                ('mar_right60', models.CharField(max_length=20, verbose_name='推介')),
                ('detail', models.TextField(verbose_name='详细情况')),
                ('url', models.CharField(max_length=20, verbose_name='相关链接')),
                ('mar_right1', models.CharField(max_length=20, verbose_name='足球大贏家')),
                ('mar_right2', models.CharField(max_length=20, verbose_name='足彩大富翁')),
                ('mar_right3', models.CharField(max_length=20, verbose_name='明報')),
                ('mar_right4', models.CharField(max_length=20, verbose_name='太 陽 報')),
                ('mar_right5', models.CharField(max_length=20, verbose_name='東方日報')),
                ('mar_right6', models.CharField(max_length=20, verbose_name='蘋果日報')),
                ('match_time', models.CharField(max_length=20, verbose_name='比赛时间')),
                ('home_team', models.CharField(max_length=20, verbose_name='主队')),
                ('guest_team', models.CharField(max_length=20, verbose_name='客队')),
                ('h_odd', models.CharField(max_length=10, verbose_name='主胜赔率')),
                ('pk_odd', models.CharField(max_length=10, verbose_name='打平赔率')),
                ('g_odd', models.CharField(max_length=10, verbose_name='客胜赔率')),
                ('full_result', models.CharField(max_length=10, verbose_name='比分')),
                ('oddstr_281_f_result', models.CharField(max_length=30, verbose_name='bet365初盘')),
                ('oddstr_281_l_result', models.CharField(max_length=30, verbose_name='bet365即时')),
                ('oddstr_115_f_result', models.CharField(max_length=30, verbose_name='威廉希尔初盘')),
                ('oddstr_115_l_result', models.CharField(max_length=30, verbose_name='威廉希尔即时')),
                ('oddstr_82_f_result', models.CharField(max_length=30, verbose_name='立博初盘')),
                ('oddstr_82_l_result', models.CharField(max_length=30, verbose_name='立博即时')),
                ('odds_3_f_result', models.CharField(max_length=30, verbose_name='Crown初盘(亚)')),
                ('odds_3_l_result', models.CharField(max_length=30, verbose_name='Crown即时(亚)')),
                ('odds_8_f_result', models.CharField(max_length=30, verbose_name='Bet365初盘(亚)')),
                ('odds_8_l_result', models.CharField(max_length=30, verbose_name='Bet365即时(亚)')),
                ('odds_14_f_result', models.CharField(max_length=30, verbose_name='韦德初盘(亚)')),
                ('odds_14_l_result', models.CharField(max_length=30, verbose_name='韦德即时(亚)')),
            ],
        ),
    ]
