# Generated by Django 2.1.3 on 2019-12-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zqfx', '0003_auto_20191215_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='zqfx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datec', models.CharField(max_length=20, verbose_name='比赛日期')),
                ('cc', models.CharField(max_length=20, verbose_name='场次')),
                ('fxs_leauge', models.CharField(blank=True, max_length=50, verbose_name='联赛')),
                ('fxs_leauge_name0', models.CharField(blank=True, max_length=50, verbose_name='主队')),
                ('fxs_leauge_name1', models.CharField(blank=True, max_length=50, verbose_name='客队')),
                ('fxs_2_02_c01', models.CharField(blank=True, max_length=50, verbose_name='彩种1')),
                ('fxs_2_02_c03', models.CharField(blank=True, max_length=50, verbose_name='推荐1')),
                ('fxs_2_03_gailus1', models.CharField(blank=True, max_length=50, verbose_name='概率1')),
                ('predictc', models.CharField(blank=True, max_length=50, verbose_name='百分比')),
                ('fxs_2_02_c01y', models.CharField(blank=True, max_length=50, verbose_name='彩种2')),
                ('fxs_2_02_c01yp', models.CharField(blank=True, max_length=50, verbose_name='盘口2')),
                ('fxs_2_02_c01yt', models.CharField(blank=True, max_length=50, verbose_name='推荐2')),
                ('fxs_2_02_c01yg', models.CharField(blank=True, max_length=50, verbose_name='概率2')),
            ],
        ),
    ]
