# Generated by Django 2.1.3 on 2019-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zqfx', '0006_leisu_now1_sporttery_tips_vipc'),
    ]

    operations = [
        migrations.AddField(
            model_name='zqfx',
            name='url',
            field=models.CharField(max_length=50, null=True, verbose_name='相关链接'),
        ),
    ]
