# Generated by Django 2.1.3 on 2019-12-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zqfx', '0007_zqfx_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zqfx',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='相关链接'),
        ),
    ]
