# Generated by Django 2.1.3 on 2019-12-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zqfx', '0008_auto_20191216_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipc',
            name='guest',
            field=models.CharField(max_length=100, null=True, verbose_name='客队'),
        ),
        migrations.AddField(
            model_name='vipc',
            name='home',
            field=models.CharField(max_length=100, null=True, verbose_name='主队'),
        ),
    ]
