# Generated by Django 2.1.3 on 2019-12-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zqfx', '0009_auto_20191216_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipc',
            name='content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
    ]
