# Generated by Django 2.1.3 on 2019-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zqfx', '0010_vipc_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipc',
            name='betting',
            field=models.CharField(max_length=100, null=True, verbose_name='投注比率'),
        ),
        migrations.AddField(
            model_name='vipc',
            name='letgoal',
            field=models.CharField(max_length=100, null=True, verbose_name='让球'),
        ),
        migrations.AddField(
            model_name='vipc',
            name='matchId',
            field=models.CharField(max_length=100, null=True, verbose_name='比赛ID'),
        ),
        migrations.AddField(
            model_name='vipc',
            name='num',
            field=models.CharField(max_length=100, null=True, verbose_name='投注人数'),
        ),
        migrations.AddField(
            model_name='vipc',
            name='ratio',
            field=models.CharField(max_length=100, null=True, verbose_name='赔率'),
        ),
        migrations.AddField(
            model_name='vipc',
            name='suggest0',
            field=models.CharField(max_length=100, null=True, verbose_name='建议'),
        ),
        migrations.AddField(
            model_name='vipc',
            name='suggest1',
            field=models.CharField(max_length=100, null=True, verbose_name='建议'),
        ),
    ]
