# Generated by Django 2.1.3 on 2019-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zqfx', '0011_auto_20191217_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='leisu',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='链接'),
        ),
    ]
