# Generated by Django 2.1.3 on 2019-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zqfx', '0012_leisu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='leisu',
            name='information',
            field=models.TextField(null=True, verbose_name='咨询'),
        ),
    ]
