# Generated by Django 2.1.3 on 2019-12-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zqfx', '0013_leisu_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='_10cjk',
            new_name='tencjk',
        ),
    ]
