# Generated by Django 2.1.3 on 2019-12-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zqfx', '0014_auto_20191218_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='guest',
            field=models.CharField(max_length=100, null=True, verbose_name='客队'),
        ),
        migrations.AddField(
            model_name='tips',
            name='home',
            field=models.CharField(max_length=100, null=True, verbose_name='主队'),
        ),
        migrations.AddField(
            model_name='tips',
            name='url',
            field=models.CharField(max_length=200, null=True, verbose_name='链接'),
        ),
    ]
